// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeHub.Data;

#nullable disable

namespace RecipeHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212114456_SeedDataRecipes")]
    partial class SeedDataRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeHub.Models.InstructionStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("step_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StepId"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<string>("StepText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("step_text");

                    b.HasKey("StepId")
                        .HasName("pk_instruction_steps");

                    b.HasIndex("RecipeId", "StepNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_instruction_steps_recipe_id_step_number");

                    b.ToTable("instruction_steps", (string)null);
                });

            modelBuilder.Entity("RecipeHub.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("ProductNamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_namn");

                    b.HasKey("ProductId")
                        .HasName("pk_products");

                    b.HasIndex("ProductNamn")
                        .IsUnique()
                        .HasDatabaseName("ix_products_product_namn");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("RecipeHub.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("RecipeCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipe_category");

                    b.Property<string>("RecipeDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recipe_description");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipe_name");

                    b.HasKey("RecipeId")
                        .HasName("pk_recipes");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("RecipeHub.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("RecipeId", "ProductId")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_recipe_ingredients_product_id");

                    b.ToTable("recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("RecipeHub.Models.InstructionStep", b =>
                {
                    b.HasOne("RecipeHub.Models.Recipe", "Recipe")
                        .WithMany("InstructionSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruction_steps_recipes_recipe_id");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeHub.Models.RecipeIngredient", b =>
                {
                    b.HasOne("RecipeHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_products_product_id");

                    b.HasOne("RecipeHub.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id");

                    b.Navigation("Product");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeHub.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("InstructionSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
